<style>
    .dropdown-content {
        max-width: 175px;
        max-height: 300px;
        overflow-y: auto;
        overflow-x: hidden; /* Add this line */
    }
</style>


<div class="dropdown">
    <!-- svelte-ignore a11y-no-noninteractive-tabindex -->
    <!-- svelte-ignore a11y-label-has-associated-control -->
    <label tabindex="0" class="btn btn-ghost">Countries</label>
    <!-- svelte-ignore a11y-no-noninteractive-tabindex -->
    <ul tabindex="0" class="z-10 dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
            <li><a href="/country/Afghanistan">Afghanistan</a></li>
            <li><a href="/country/Albania">Albania</a></li>
            <li><a href="/country/Algeria">Algeria</a></li>
            <li><a href="/country/Andorra">Andorra</a></li>
            <li><a href="/country/Angola">Angola</a></li>
            <li><a href="/country/Antigua-and-barbuda">Antigua and Barbuda</a></li>
            <li><a href="/country/Argentina">Argentina</a></li>
            <li><a href="/country/Armenia">Armenia</a></li>
            <li><a href="/country/Aruba">Aruba</a></li>
            <li><a href="/country/Australia">Australia</a></li>
            <li><a href="/country/Austria">Austria</a></li>
            <li><a href="/country/Azerbaijan">Azerbaijan</a></li>
            <li><a href="/country/Bahamas">Bahamas</a></li>
            <li><a href="/country/Bahrain">Bahrain</a></li>
            <li><a href="/country/Bangladesh">Bangladesh</a></li>
            <li><a href="/country/Barbados">Barbados</a></li>
            <li><a href="/country/Belarus">Belarus</a></li>
            <li><a href="/country/Belgium">Belgium</a></li>
            <li><a href="/country/Belize">Belize</a></li>
            <li><a href="/country/Benin">Benin</a></li>
            <li><a href="/country/Bermuda">Bermuda</a></li>
            <li><a href="/country/Bhutan">Bhutan</a></li>
            <li><a href="/country/Bolivia">Bolivia</a></li>
            <li><a href="/country/Bosnia-and-herzegovina">Bosnia and Herzegovina</a></li>
            <li><a href="/country/Botswana">Botswana</a></li>
            <li><a href="/country/Brazil">Brazil</a></li>
            <li><a href="/country/British-virgin-islands">British Virgin Islands</a></li>
            <li><a href="/country/Brunei">Brunei</a></li>
            <li><a href="/country/Bulgaria">Bulgaria</a></li>
            <li><a href="/country/Burkina-faso">Burkina Faso</a></li>
            <li><a href="/country/Burundi">Burundi</a></li>
            <li><a href="/country/Cambodia">Cambodia</a></li>
            <li><a href="/country/Cameroon">Cameroon</a></li>
            <li><a href="/country/Canada">Canada</a></li>
            <li><a href="/country/Cape-verde">Cape Verde</a></li>
            <li><a href="/country/Cayman-islands">Cayman Islands</a></li>
            <li><a href="/country/Central-african-republic">Central African Republic</a></li>
            <li><a href="/country/Chad">Chad</a></li>
            <li><a href="/country/Chile">Chile</a></li>
            <li><a href="/country/China">China</a></li>
            <li><a href="/country/Colombia">Colombia</a></li>
            <li><a href="/country/Comoros">Comoros</a></li>
            <li><a href="/country/Cook-islands">Cook Islands</a></li>
            <li><a href="/country/Costa-rica">Costa Rica</a></li>
            <li><a href="/country/Croatia">Croatia</a></li>
            <li><a href="/country/Cuba">Cuba</a></li>
            <li><a href="/country/Curacao">Curaçao</a></li>
            <li><a href="/country/Cyprus">Cyprus</a></li>
            <li><a href="/country/Czech-republic">Czech Republic</a></li>
            <li><a href="/country/Democratic-republic-of-the-congo">Democratic Republic of the Congo</a></li>
            <li><a href="/country/Denmark">Denmark</a></li>
            <li><a href="/country/Djibouti">Djibouti</a></li>
            <li><a href="/country/Dominica">Dominica</a></li>
            <li><a href="/country/Dominican-republic">Dominican Republic</a></li>
            <li><a href="/country/East-timor">East Timor</a></li>
            <li><a href="/country/Ecuador">Ecuador</a></li>
            <li><a href="/country/Egypt">Egypt</a></li>
            <li><a href="/country/El-salvador">El Salvador</a></li>
            <li><a href="/country/Equatorial-guinea">Equatorial Guinea</a></li>
            <li><a href="/country/Eritrea">Eritrea</a></li>
            <li><a href="/country/Estonia">Estonia</a></li>
            <li><a href="/country/Eswatini">Eswatini</a></li>
            <li><a href="/country/Ethiopia">Ethiopia</a></li>
            <li><a href="/country/Falkland-islands">Falkland Islands</a></li>
            <li><a href="/country/Faroe-islands">Faroe Islands</a></li>
            <li><a href="/country/Fiji">Fiji</a></li>
            <li><a href="/country/Finland">Finland</a></li>
            <li><a href="/country/France">France</a></li>
            <li><a href="/country/French-polynesia">French Polynesia</a></li>
            <li><a href="/country/Gabon">Gabon</a></li>
            <li><a href="/country/Gambia">Gambia</a></li>
            <li><a href="/country/Georgia">Georgia</a></li>
            <li><a href="/country/Germany">Germany</a></li>
            <li><a href="/country/Ghana">Ghana</a></li>
            <li><a href="/country/Gibraltar">Gibraltar</a></li>
            <li><a href="/country/Greece">Greece</a></li>
            <li><a href="/country/Greenland">Greenland</a></li>
            <li><a href="/country/Grenada">Grenada</a></li>
            <li><a href="/country/Guam">Guam</a></li>
            <li><a href="/country/Guatemala">Guatemala</a></li>
            <li><a href="/country/Guernsey">Guernsey</a></li>
            <li><a href="/country/Guinea">Guinea</a></li>
            <li><a href="/country/Guinea-bissau">Guinea-Bissau</a></li>
            <li><a href="/country/Guyana">Guyana</a></li>
            <li><a href="/country/Haiti">Haiti</a></li>
            <li><a href="/country/Honduras">Honduras</a></li>
            <li><a href="/country/Hong-kong">Hong Kong</a></li>
            <li><a href="/country/Hungary">Hungary</a></li>
            <li><a href="/country/Iceland">Iceland</a></li>
            <li><a href="/country/India">India</a></li>
            <li><a href="/country/Indonesia">Indonesia</a></li>
            <li><a href="/country/Iran">Iran</a></li>
            <li><a href="/country/Iraq">Iraq</a></li>
            <li><a href="/country/Ireland">Ireland</a></li>
            <li><a href="/country/Isle-of-man">Isle of Man</a></li>
            <li><a href="/country/Israel">Israel</a></li>
            <li><a href="/country/Italy">Italy</a></li>
            <li><a href="/country/Ivory-coast">Ivory Coast</a></li>
            <li><a href="/country/Jamaica">Jamaica</a></li>
            <li><a href="/country/Japan">Japan</a></li>
            <li><a href="/country/Jersey">Jersey</a></li>
            <li><a href="/country/Jordan">Jordan</a></li>
            <li><a href="/country/Kazakhstan">Kazakhstan</a></li>
            <li><a href="/country/Kenya">Kenya</a></li>
            <li><a href="/country/Kiribati">Kiribati</a></li>
            <li><a href="/country/Kosovo">Kosovo</a></li>
            <li><a href="/country/Kuwait">Kuwait</a></li>
            <li><a href="/country/Kyrgyzstan">Kyrgyzstan</a></li>
            <li><a href="/country/Laos">Laos</a></li>
            <li><a href="/country/Latvia">Latvia</a></li>
            <li><a href="/country/Lebanon">Lebanon</a></li>
            <li><a href="/country/Lesotho">Lesotho</a></li>
            <li><a href="/country/Liberia">Liberia</a></li>
            <li><a href="/country/Libya">Libya</a></li>
            <li><a href="/country/Liechtenstein">Liechtenstein</a></li>
            <li><a href="/country/Lithuania">Lithuania</a></li>
            <li><a href="/country/Luxembourg">Luxembourg</a></li>
            <li><a href="/country/Macao">Macao</a></li>
            <li><a href="/country/Madagascar">Madagascar</a></li>
            <li><a href="/country/Malawi">Malawi</a></li>
            <li><a href="/country/Malaysia">Malaysia</a></li>
            <li><a href="/country/Maldives">Maldives</a></li>
            <li><a href="/country/Mali">Mali</a></li>
            <li><a href="/country/Malta">Malta</a></li>
            <li><a href="/country/Marshall-islands">Marshall Islands</a></li>
            <li><a href="/country/Mauritania">Mauritania</a></li>
            <li><a href="/country/Mauritius">Mauritius</a></li>
            <li><a href="/country/Mexico">Mexico</a></li>
            <li><a href="/country/Micronesia">Micronesia</a></li>
            <li><a href="/country/Moldova">Moldova</a></li>
            <li><a href="/country/Monaco">Monaco</a></li>
            <li><a href="/country/Mongolia">Mongolia</a></li>
            <li><a href="/country/Montenegro">Montenegro</a></li>
            <li><a href="/country/Montserrat">Montserrat</a></li>
            <li><a href="/country/Morocco">Morocco</a></li>
            <li><a href="/country/Mozambique">Mozambique</a></li>
            <li><a href="/country/Myanmar">Myanmar</a></li>
            <li><a href="/country/Namibia">Namibia</a></li>
            <li><a href="/country/Nauru">Nauru</a></li>
            <li><a href="/country/Nepal">Nepal</a></li>
            <li><a href="/country/Netherlands">Netherlands</a></li>
            <li><a href="/country/New-caledonia">New Caledonia</a></li>
            <li><a href="/country/New-zealand">New Zealand</a></li>
            <li><a href="/country/Nicaragua">Nicaragua</a></li>
            <li><a href="/country/Niger">Niger</a></li>
            <li><a href="/country/Nigeria">Nigeria</a></li>
            <li><a href="/country/Niue">Niue</a></li>
            <li><a href="/country/North-korea">North Korea</a></li>
            <li><a href="/country/North-macedonia">North Macedonia</a></li>
            <li><a href="/country/Northern-mariana-islands">Northern Mariana Islands</a></li>
            <li><a href="/country/Norway">Norway</a></li>
            <li><a href="/country/Oman">Oman</a></li>
            <li><a href="/country/Pakistan">Pakistan</a></li>
            <li><a href="/country/Palau">Palau</a></li>
            <li><a href="/country/Palestine">Palestine</a></li>
            <li><a href="/country/Panama">Panama</a></li>
            <li><a href="/country/Papua-new-guinea">Papua New Guinea</a></li>
            <li><a href="/country/Paraguay">Paraguay</a></li>
            <li><a href="/country/Peru">Peru</a></li>
            <li><a href="/country/Philippines">Philippines</a></li>
            <li><a href="/country/Poland">Poland</a></li>
            <li><a href="/country/Portugal">Portugal</a></li>
            <li><a href="/country/Puerto-rico">Puerto Rico</a></li>
            <li><a href="/country/Qatar">Qatar</a></li>
            <li><a href="/country/Republic-of-the-congo">Republic of the Congo</a></li>
            <li><a href="/country/Romania">Romania</a></li>
            <li><a href="/country/Russia">Russia</a></li>
            <li><a href="/country/Rwanda">Rwanda</a></li>
            <li><a href="/country/Saint-kitts-and-nevis">Saint Kitts and Nevis</a></li>
            <li><a href="/country/Saint-lucia">Saint Lucia</a></li>
            <li><a href="/country/Saint-martin">Saint Martin</a></li>
            <li><a href="/country/Saint-pierre-and-miquelon">Saint Pierre and Miquelon</a></li>
            <li><a href="/country/Saint-vincent-and-the-grenadines">Saint Vincent and the Grenadines</a></li>
            <li><a href="/country/Samoa">Samoa</a></li>
            <li><a href="/country/San-marino">San Marino</a></li>
            <li><a href="/country/Sao-tome-and-principe">Sao Tome and Principe</a></li>
            <li><a href="/country/Saudi-arabia">Saudi Arabia</a></li>
            <li><a href="/country/Senegal">Senegal</a></li>
            <li><a href="/country/Serbia">Serbia</a></li>
            <li><a href="/country/Seychelles">Seychelles</a></li>
            <li><a href="/country/Sierra-leone">Sierra Leone</a></li>
            <li><a href="/country/Singapore">Singapore</a></li>
            <li><a href="/country/Sint-maarten">Sint Maarten</a></li>
            <li><a href="/country/Slovakia">Slovakia</a></li>
            <li><a href="/country/Slovenia">Slovenia</a></li>
            <li><a href="/country/Solomon-islands">Solomon Islands</a></li>
            <li><a href="/country/Somalia">Somalia</a></li>
            <li><a href="/country/South-africa">South Africa</a></li>
            <li><a href="/country/South-korea">South Korea</a></li>
            <li><a href="/country/South-sudan">South Sudan</a></li>
            <li><a href="/country/Spain">Spain</a></li>
            <li><a href="/country/Sri-lanka">Sri Lanka</a></li>
            <li><a href="/country/Sudan">Sudan</a></li>
            <li><a href="/country/Suriname">Suriname</a></li>
            <li><a href="/country/Sweden">Sweden</a></li>
            <li><a href="/country/Switzerland">Switzerland</a></li>
            <li><a href="/country/Syria">Syria</a></li>
            <li><a href="/country/Taiwan">Taiwan</a></li>
            <li><a href="/country/Tajikistan">Tajikistan</a></li>
            <li><a href="/country/Tanzania">Tanzania</a></li>
            <li><a href="/country/Thailand">Thailand</a></li>
            <li><a href="/country/Togo">Togo</a></li>
            <li><a href="/country/Tokelau">Tokelau</a></li>
            <li><a href="/country/Tonga">Tonga</a></li>
            <li><a href="/country/Trinidad-and-tobago">Trinidad and Tobago</a></li>
            <li><a href="/country/Tunisia">Tunisia</a></li>
            <li><a href="/country/Turkey">Turkey</a></li>
            <li><a href="/country/Turkmenistan">Turkmenistan</a></li>
            <li><a href="/country/Turks-and-caicos-islands">Turks and Caicos Islands</a></li>
            <li><a href="/country/Tuvalu">Tuvalu</a></li>
            <li><a href="/country/Uganda">Uganda</a></li>
            <li><a href="/country/Ukraine">Ukraine</a></li>
            <li><a href="/country/United-arab-emirates">United Arab Emirates</a></li>
            <li><a href="/country/United-kingdom">United Kingdom</a></li>
            <li><a href="/country/United-states">United States</a></li>
            <li><a href="/country/Uruguay">Uruguay</a></li>
            <li><a href="/country/Uzbekistan">Uzbekistan</a></li>
            <li><a href="/country/Vanuatu">Vanuatu</a></li>
            <li><a href="/country/Vatican-city">Vatican City</a></li>
            <li><a href="/country/Venezuela">Venezuela</a></li>
            <li><a href="/country/Vietnam">Vietnam</a></li>
            <li><a href="/country/Virgin-islands-british">Virgin Islands, British</a></li>
            <li><a href="/country/Virgin-islands-us">Virgin Islands, U.S.</a></li>
            <li><a href="/country/Wallis-and-futuna">Wallis and Futuna</a></li>
            <li><a href="/country/Yemen">Yemen</a></li>
            <li><a href="/country/Zambia">Zambia</a></li>
            <li><a href="/country/Zimbabwe">Zimbabwe</a></li>  
    </ul>
  </div>